---
- hosts: locators,datanodes
  become: no
  vars:
      ansible_ssh_user: ec2-user
  tasks:
    - name: make sure at least one locator is started so the shutdown will work 
      command: python gf.py start  gem1101-locator
      args:
          chdir: /runtime/gem_cluster_1
      when: inventory_hostname == play_hosts[0]
        
    - name: stop the cluster 
      command: 
      args:
          chdir: /runtime/gem_cluster_1
          argv:
              - /runtime/gemfire/bin/gfsh 
              - -e 
              - connect --locator=192.168.1.101[10000]
              - -e 
              - shutdown --include-locators=true  
      when: inventory_hostname == play_hosts[0]
        
    - name: remove the cluster home dir
      file: 
            path: /runtime/gem_cluster_1
            state: absent
        
    - name: create the cluster home dir
      file: 
        path: /runtime/gem_cluster_1
        state: directory
        owner: ec2-user
        group: ec2-user
        