---
- hosts: locators
  vars:
    ansible_ssh_private_key_file: ihg-keypair.pem
  environment:
    JAVA_HOME: /runtime/java
  remote_user: ec2-user
  become: no
  tasks:
  - name: copy gemfire-starter-2.zip to cluster home
    copy:
      src: gemfire-starter-2.zip
      dest: /runtime/gem_cluster_{{ dsid}}/gemfire-starter-2.zip

  - name: start the cluster
    command: /usr/bin/python gf.py start
    args:
      chdir: /runtime/gem_cluster_{{ dsid }}

  - name: import the cluster configuration
    command: /runtime/gemfire/bin/gfsh -e "connect --locator=localhost[10000]" -e "import cluster-configuration --zip-file-name=/runtime/gem_cluster_{{ dsid}}/gemfire-starter-2.zip"

  - name: stop the cluster
    command: /runtime/gemfire/bin/gfsh -e "connect --locator=localhost[10000]" -e "shutdown --include-locators=true"
